tasks:
  - source: notebooks/01_preprocess.ipynb
    product:
      nb: output/01_preprocess.ipynb
      train: data/processed/train.parquet
      val: data/processed/val.parquet
      test: data/processed/test.parquet
      config: data/processed/preprocessing_config.json

  - source: notebooks/02_train.ipynb
    product:
      nb: output/02_train.ipynb
      model: checkpoints/best_model.pt
      metrics: checkpoints/best_model_info.json
      results: checkpoints/training_results.json

  - source: notebooks/03_benchmark.ipynb
    product:
      nb: output/03_benchmark.ipynb
    params:
      model_path: "checkpoints/best_model.pt"